[package]
name = "sigma-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
rusigma = { path = "rusigma" }
home = "0.5.3"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
tabled = "0.8.0"